TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Neoslive.Hybridsearch.Neos.Demo': TRUE

Neoslive:
  Hybridsearch:
    Realtime: true
    Firebase:
      endpoint: 'https://neos-live.firebaseio.com/'
    Filter:
      GrantParentNodeTypeFilter: '[instanceof TYPO3.Neos:Document]'
      ParentNodeTypeFilter: '[instanceof TYPO3.Neos.NodeTypes:Headline]'
      NodeTypeFilter: '[instanceof Neoslive.Hybridsearch:Content]'



